* Решение ТЗ для собеседования на Роль Java Developer-а

  
** Как исполоьзовать.

   =public static void main()= в данном репозитории отсутствует. Вместо этого проверка осуществляется при помощи тестов, как юнитных так и интеграционных.

   
** Компактность сериализованной строки

   В данном репозитории два вида сериализации: фиксированная и вариабильная. В одном случае используются нативные строки java, в другом UTF-8 кодированные. В данном случае я вопсользовался ограничением по размеру вводимых элементов массива, чтобы использовать вариабильную кодировку UTF-8 напрямую. Для 64-х битных =int=, такой подход не подойдёт.

   На всякий случай я имплементировал =RunLengthEncoding=, который помог бы в случае если бы чисел было бы в среднем случае больше. Так как =2*200 < 1000=, эта кодировка почти всегда будет увеличивать размер записанной строки.

   Случаи когда это могло бы увеличить компактность результатов могут встречаться и для малых массивов, но для правильной импелементации которая всегда выбирает подходящую кодировку, нужно бы было использовать ещё один байт. Учитывая поставленную задачу я счёл это расточительным, однако энкодер оставил как есть.

   Библиотек избегал по возможности и специально, (в обратном случае можно было бы добавить ещё и =deflate=).

   Прошу воспользоваться этой возможностью и осмотреть другой мой код.

   АП
   
** Лицензия

   MIT. 
